import JSZip from "jszip";
import { idGen } from "./util";

const BUILD_MAP_FUNC = 'build_map';
const MAP_INFO_FILE_NAME = 'map_info';
const PACK_DESCRIPTION = 'Animated map arts generated by RandomPerson3465.github.io';
export const ITEM_FRAME_AIR_TAG = 1;

class Vector3 {
    dx: number
    dy: number
    dz: number
    constructor(dx: number, dy: number, dz: number) {
        this.dx = dx;
        this.dy = dy;
        this.dz = dz;
    }
    toString() {
        return `~${this.dx || ''} ~${this.dy || ''} ~${this.dz || ''}`;
    }
    static linCombo(a: number, u: Vector3, b: number, v: Vector3) : Vector3 {
        return new Vector3(a * u.dx + b * v.dx, a * u.dy + b * v.dy, a * u.dz + b * v.dz);
    }
}

const DIRECTIONS = [
    [new Vector3(1, 0, 0), new Vector3(0, 0, -1)],
    [new Vector3(1, 0, 0), new Vector3(0, 0, 1)],
    [new Vector3(-1, 0, 0), new Vector3(0, -1, 0)],
    [new Vector3(1, 0, 0), new Vector3(0, -1, 0)],
    [new Vector3(0, 0, 1), new Vector3(0, -1, 0)],
    [new Vector3(0, 0, -1), new Vector3(0, -1, 0)]
]

export interface mapInfo {
    mapName: string,
    mapsWidth: number,
    mapsHeight: number,
    ticksPerFrame: number,
    startingIndex: number,
    frames: number,
}

function generateBuildMapCommand_1_20_5(id: string, mapData: mapInfo[]) {
    let result = '';
    for (const info of mapData) {
        for (let f = 0; f < 24; ++f) {
            const facing = f >> 2;
            const glow = f & 2 ? 'glow_' : '';
            const invis = f & 1;
            const RIGHT = DIRECTIONS[facing][0];
            const DOWN = DIRECTIONS[facing][1];
            for (let y = 0; y < info.mapsHeight; ++y) {
                for (let x = 0; x < info.mapsWidth; ++x) {
                    if (x === 0 && y === 0) continue;
                    result += `execute at @e[type=${glow}item_frame,tag=${info.mapName},nbt={Facing:${facing}b,Invisible:${invis}b,Air:${ITEM_FRAME_AIR_TAG}s}] run summon ${glow}item_frame ${Vector3.linCombo(x, RIGHT, y, DOWN)} {Facing:${facing}b,Invisible:${invis}b,Item:{id:"filled_map",count:1,components:{"map_id":${info.startingIndex + y * info.mapsWidth + x}}}}\n`
                }
            }
        }
        result += `execute as @e[type=item_frame,tag=${info.mapName},nbt={Air:${ITEM_FRAME_AIR_TAG}s}] run data merge entity @s {Air:300s}\nexecute as @e[type=glow_item_frame,tag=${info.mapName},nbt={Air:${ITEM_FRAME_AIR_TAG}s}] run data merge entity @s {Air:300s}\n`
    }
    result += `schedule function ${id}:${BUILD_MAP_FUNC} 1t`;
    return result;
}

export async function generateDataPack(mapData: mapInfo[]) {
  const datapack = new JSZip();
  const id = idGen();
  const meta = {
    pack: {
      description: PACK_DESCRIPTION,
      min_format: 41,
      max_format: 2147483647
    }
  }
  const mapInfoFile = {
    data: mapData
  }
  datapack.file('pack.mcmeta', JSON.stringify(meta));
  datapack.file(MAP_INFO_FILE_NAME + '.json', JSON.stringify(mapInfoFile));
  const dataFolder = datapack.folder('data')!;
  const mcLoadFolder = dataFolder.folder('minecraft')!.folder('tags')!.folder('function')!;
  const loadJson = {
    replace: false,
    values: [id + ':' + BUILD_MAP_FUNC]
  }
  mcLoadFolder.file('load.json', JSON.stringify(loadJson));
  const funcFolder = dataFolder.folder(id)!.folder('function')!;
  
  funcFolder.file(BUILD_MAP_FUNC + '.mcfunction', generateBuildMapCommand_1_20_5(id, mapData));
  return datapack.generateAsync({ type: 'blob' });
}