import JSZip from "jszip";
import { idGen } from "./util";
import * as versions from "./mc_versions";

export const MAP_INFO_FILE_NAME = 'map_info';
const PACK_DESCRIPTION = 'Animated map arts generated by RandomPerson3465.github.io';
export const ITEM_FRAME_AIR_TAG = 1;
export const PREFIX = 'animated_map_art_';
export const NEW_ID_SUB = '%new_id%';

class Vector3 {
    dx: number
    dy: number
    dz: number
    constructor(dx: number, dy: number, dz: number) {
        this.dx = dx;
        this.dy = dy;
        this.dz = dz;
    }
    toString() {
        return `~${this.dx || ''} ~${this.dy || ''} ~${this.dz || ''}`;
    }
    static linCombo(a: number, u: Vector3, b: number, v: Vector3): Vector3 {
        return new Vector3(a * u.dx + b * v.dx, a * u.dy + b * v.dy, a * u.dz + b * v.dz);
    }
}

const DIRECTIONS = [
    [new Vector3(1, 0, 0), new Vector3(0, 0, -1)],
    [new Vector3(1, 0, 0), new Vector3(0, 0, 1)],
    [new Vector3(-1, 0, 0), new Vector3(0, -1, 0)],
    [new Vector3(1, 0, 0), new Vector3(0, -1, 0)],
    [new Vector3(0, 0, 1), new Vector3(0, -1, 0)],
    [new Vector3(0, 0, -1), new Vector3(0, -1, 0)]
]

export interface MapInfo {
    mapName: string,
    mapsWidth: number,
    mapsHeight: number,
    ticksPerFrame: number,
    startingIndex: number,
    frames: number,
}

export interface MapInfoFile {
    id: string,
    version: number,
    data: MapInfo[]
}

function isValidMapInfo(value: unknown): value is MapInfo {
    return (value != null && typeof value === 'object') &&
    ('mapName' in value && typeof value.mapName === 'string' && value.mapName.length > 0) &&
    ('mapsWidth' in value && typeof value.mapsWidth === 'number' 
        && value.mapsWidth % 1 === 0 && value.mapsWidth > 0) &&
    ('mapsHeight' in value && typeof value.mapsHeight === 'number' 
        && value.mapsHeight % 1 === 0 && value.mapsHeight > 0) &&
    ('ticksPerFrame' in value && typeof value.ticksPerFrame === 'number' 
        && value.ticksPerFrame % 1 === 0 && value.ticksPerFrame > 0) &&
    ('startingIndex' in value && typeof value.startingIndex === 'number' 
        && value.startingIndex % 1 === 0 && value.startingIndex >= 0) &&
    ('frames' in value && typeof value.frames === 'number' 
        && value.frames % 1 === 0 && value.frames > 0)
}

export function isValidMapInfoFile(value: unknown): value is MapInfoFile {
    return (value != null && typeof value == 'object') &&
    ('id' in value && typeof value.id === 'string' && value.id.length > 0) &&
    ('version' in value && typeof value.version === 'number' && value.version % 1 === 0) &&
    ('data' in value && typeof value.data === 'object' && value.data instanceof Array) && 
    (value.data.every(x => isValidMapInfo(x)));
}

function generateBuildMapCommand_1_20_5(id: string, namespace: string, mapData: MapInfo[], funcFolder: JSZip) {
    let result = `execute as @a run execute unless score @s c_${id} matches -1.. run scoreboard players set @s c_${id} -1\n`;
    for (const info of mapData) {

        if (info.frames > 1) {
            const mapsSize = info.mapsWidth * info.mapsHeight;
            const nextIndex = info.startingIndex + mapsSize * info.frames;
            funcFolder.file(`animate_${info.startingIndex}.mcfunction`,
                `scoreboard players set ${info.startingIndex} s_${id} ${mapsSize}\n`
                + `scoreboard players set ${info.startingIndex}n s_${id} ${info.startingIndex}\n`
                + `execute as @e[type=item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute unless score @s f_${id} matches 0.. run scoreboard players operation @s f_${id} = @s i_${id}\n`
                + `execute as @e[type=glow_item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute unless score @s f_${id} matches 0.. run scoreboard players operation @s f_${id} = @s i_${id}\n`
                + `execute as @e[type=item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute unless score @s f_${id} matches ${nextIndex}.. run scoreboard players operation @s f_${id} += ${info.startingIndex} s_${id}\n`
                + `execute as @e[type=item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute if score @s f_${id} matches ${nextIndex}.. run scoreboard players operation @s f_${id} = @s i_${id}\n`
                + `execute as @e[type=glow_item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute unless score @s f_${id} matches ${nextIndex}.. run scoreboard players operation @s f_${id} += ${info.startingIndex} s_${id}\n`
                + `execute as @e[type=glow_item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute if score @s f_${id} matches ${nextIndex}.. run scoreboard players operation @s f_${id} = @s i_${id}\n`
                + `execute as @e[type=item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute if score @s f_${id} matches 0.. run execute store result entity @s Item.components.minecraft:map_id int 1 run scoreboard players get @s f_${id}\n`
                + `execute as @e[type=glow_item_frame,tag=${info.mapName},nbt=!{Air:${ITEM_FRAME_AIR_TAG}s}] run execute if score @s f_${id} matches 0.. run execute store result entity @s Item.components.minecraft:map_id int 1 run scoreboard players get @s f_${id}\n`
                + `schedule function ${namespace}:animate_${info.startingIndex} ${info.ticksPerFrame}t`
            );
            let cacheFunc = '';
            for (let i = info.startingIndex; i < nextIndex; ++i) {
                cacheFunc += `execute as @a run execute if score @s c_${id} matches ${i} run item replace entity @s weapon.offhand with filled_map[map_id=${i}]\n`
            }
            cacheFunc += (`execute as @a run execute if score @s c_${id} matches ${nextIndex - 1} run scoreboard players set @s c_${id} -1\n`
                + `execute as @a run execute if score @s c_${id} matches ${info.startingIndex}..${nextIndex - 2} run scoreboard players add @s c_${id} 1\n`
                + `schedule function ${namespace}:cache_${info.startingIndex} 1t\n`);
            funcFolder.file(`cache_${info.startingIndex}.mcfunction`, cacheFunc);
        }

        for (let f = 0; f < 24; ++f) {
            const facing = f >> 2;
            const glow = f & 2 ? 'glow_' : '';
            const invis = f & 1;
            const RIGHT = DIRECTIONS[facing][0];
            const DOWN = DIRECTIONS[facing][1];
            for (let y = 0; y < info.mapsHeight; ++y) {
                for (let x = 0; x < info.mapsWidth; ++x) {
                    if (x === 0 && y === 0) continue;
                    result += `execute at @e[type=${glow}item_frame,tag=${info.mapName},nbt={Facing:${facing}b,Invisible:${invis}b,Air:${ITEM_FRAME_AIR_TAG}s}] run summon ${glow}item_frame ${Vector3.linCombo(x, RIGHT, y, DOWN)} {Facing:${facing}b,Invisible:${invis}b,Item:{id:"filled_map",count:1,components:{"map_id":${info.startingIndex + y * info.mapsWidth + x}}},Tags:["${info.mapName}"]}\n`
                }
            }
        }
        result += (`execute as @e[type=item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run execute store result score @s s_${id} run data get entity @s Item.components.minecraft:map_id\n`
            + `execute as @e[type=item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run scoreboard players operation @s s_${id} %= ${info.startingIndex} s_${id}\n`
            + `execute as @e[type=item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run scoreboard players operation @s s_${id} += ${info.startingIndex}n s_${id}\n`
            + `execute as @e[type=item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run scoreboard players operation @s i_${id} = @s s_${id}\n`
            + `execute as @e[type=glow_item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run execute store result score @s i_${id} run data get entity @s Item.components.minecraft:map_id\n`
             + `execute as @e[type=glow_item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run scoreboard players operation @s s_${id} %= ${info.startingIndex} s_${id}\n`
            + `execute as @e[type=glow_item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run scoreboard players operation @s s_${id} += ${info.startingIndex}n s_${id}\n`
            + `execute as @e[type=glow_item_frame,tag=${info.mapName}] run execute unless score @s i_${id} matches 0.. run scoreboard players operation @s i_${id} = @s s_${id}\n`
            + `execute as @e[type=item_frame,tag=${info.mapName},nbt={Air:${ITEM_FRAME_AIR_TAG}s}] run data merge entity @s {Air:300s}\n`
            + `execute as @e[type=glow_item_frame,tag=${info.mapName},nbt={Air:${ITEM_FRAME_AIR_TAG}s}] run data merge entity @s {Air:300s}\n`)
    }
    result += `schedule function ${namespace}:build_map 1t`;
    return result;
}

export function generateCleanFunction(id: string) {
    return (`scoreboard objectives remove i_${id}\n`
        + `scoreboard objectives remove f_${id}\n`
        + `scoreboard objectives remove s_${id}\n`
        + `scoreboard objectives remove c_${id}\n`);
}

export async function generateDataPack(mapData: MapInfo[], version: number, cleanOld?: string) {
    const datapack = new JSZip();
    const id = idGen(14);
    const namespace = PREFIX + id;
    let meta;
    if (version >= versions.MC_1_21) {
        // Pack format 45 renames the function folder from "functions" to "function"
        // Pack format 81 is the last version that requires the supported_formats field.
        meta = {
            pack: {
                description: PACK_DESCRIPTION,
                supported_formats: [45, 81],
                pack_format: 45,
                min_format: 45,
                max_format: 2147483647
            }
        }
    } else {
        // Pack format 41 is version 1.20.5 which introduces new command synatx/item components
        meta = {
            pack: {
                description: PACK_DESCRIPTION,
                supported_formats: [41, 44],
                pack_format: 41
            }
        }
    }
    const mapInfoFile = {
        id: id,
        version: version,
        data: mapData
    }
    datapack.file('pack.mcmeta', JSON.stringify(meta));
    datapack.file(MAP_INFO_FILE_NAME + '.json', JSON.stringify(mapInfoFile));
    const dataFolder = datapack.folder('data')!;
    const mcLoadFolder = dataFolder.folder('minecraft')!.folder('tags')!
        .folder(version >= versions.MC_1_21 ? 'function' : 'functions')!;
    const loadJson = {
        replace: false,
        values: [namespace + ':starter']
    }
    mcLoadFolder.file('load.json', JSON.stringify(loadJson));
    const funcFolder = dataFolder.folder(namespace)!
        .folder(version >= versions.MC_1_21 ? 'function' : 'functions')!;

    // Scoreboard objectives are 16 characters for compatibility reasons (pre-1.18)
    let starterFunc = `scoreboard objectives add i_${id} dummy\n` // init
        + `scoreboard objectives add f_${id} dummy\n` // frame
        + `scoreboard objectives add s_${id} dummy\n` // size
        + `scoreboard objectives add c_${id} dummy\n`; // cache scoreboard

    if (cleanOld) {
        starterFunc += `execute unless score $cleaned i_${id} matches 1 run function ${namespace}:clean_old\n`;
        funcFolder.file('clean_old.mcfunction', cleanOld.replaceAll(NEW_ID_SUB, id) + `scoreboard players set $cleaned i_${id} 1\n`);
    }

    for (const info of mapData) {
        if (info.frames > 1) {
            starterFunc += `schedule function ${namespace}:animate_${info.startingIndex} ${info.ticksPerFrame}t\n`;
            starterFunc += `function ${namespace}:cache_${info.startingIndex}\n`;
        }
    }


    funcFolder.file('clean.mcfunction', generateCleanFunction(id));

    funcFolder.file('starter.mcfunction', starterFunc + (starterFunc.endsWith('\n') ? '' : '\n') + `function ${namespace}:build_map`);

    funcFolder.file('build_map.mcfunction', generateBuildMapCommand_1_20_5(id, namespace, mapData, funcFolder));
    return {
        pack: await datapack.generateAsync({
            type: 'blob',
            compression: "DEFLATE",
            compressionOptions: {
                level: 9
            }
        }),
        id: id,
    };
}